name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - time
  - pandas
  - pip
  - pip:
    - ipywidgets
    - collections
    - IPython.display
    - matplotlib
    - plotly
    - threading
    - bokeh
    - math
    - random
    - threading
